In [1]:
import selenium
from selenium import webdriver
import time
import pandas as pd

In [2]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import TimeoutException

## 1. Scrape the details of most viewed videos on YouTube from Wikipedia: Url= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos. You need to find following details:Rank, Name, Artist, Upload Date, Views

In [3]:
# Function Definition
def youtube_videos(url):
    driver = webdriver.Chrome("C:\\chromedriver.exe")
    driver.get(url)
    time.sleep(10)
    
#     Let's create empty lists to store necessary information
    rank = []
    name = []
    artist = []
    upload_date = []
    views = []
    
#     extracting rank
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[1]"):
        rank.append(i.text)
#     extracting name
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[2]"):
        name.append(i.text)
#     extracting artist
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[3]"):
        artist.append(i.text)
#     extracting upload_date
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[5]"):
        upload_date.append(i.text)
#     extracting views
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[4]"):
        views.append(i.text)
    
    df = pd.DataFrame({})
    df['Rank']=rank[:30]
    df['Name']=name[:30]
    df['Artist']=artist[:30]
    df['Upload Date']=upload_date[:30]
    df['Views(Billions)']=views[:30]
    
    driver.close()
    
    return df


# Calling Function
youtube_videos('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

,Rank,Name,Artist,Upload Date,Views(Billions)
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,"June 17, 2016",8.43
1,2.,"""Despacito""[24]",Luis Fonsi,"January 12, 2017",7.32
2,3.,"""Shape of You""[25]",Ed Sheeran,"January 30, 2017",5.29
3,4.,"""Johny Johny Yes Papa""[26]",LooLoo Kids,"October 8, 2016",5.22
4,5.,"""See You Again""[27]",Wiz Khalifa,"April 6, 2015",5.08
5,6.,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,"January 31, 2012",4.43
6,7.,"""Uptown Funk""[31]",Mark Ronson,"November 19, 2014",4.16
7,8.,"""Gangnam Style""[32]",Psy,"July 15, 2012",4.05
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[34]",Miroshka TV,"February 27, 2018",3.96
9,10.,"""Bath Song""[35]",Cocomelon – Nursery Rhymes,"May 2, 2018",3.94
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,"March 6, 2014",3.77
11,12.,"""Sugar""[37]",Maroon 5,"January 14, 2015",3.45
12,13.,"""Sorry""[38]",Justin Bieber,"October 22, 2015",3.43
13,14.,"""Roar""[39]",Katy Perry,"September 5, 2013",3.33
14,15.,"""Dame Tu Cosita""[40]",El Chombo,"April 5, 2018",3.28
15,16.,"""Counting Stars""[41]",OneRepublic,"May 31, 2013",3.27
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,"October 7, 2014",3.24
17,18.,"""Dark Horse""[43]",Katy Perry,"February 20, 2014",3.05
18,19.,"""Shake It Off""[44]",Taylor Swift,"August 18, 2014",3.05
19,20.,"""Faded""[45]",Alan Walker,"December 3, 2015",3.05
20,21.,"""Lean On""[46]",Major Lazer Official,"March 22, 2015",3.02
21,22.,"""Bailando""[47]",Enrique Iglesias,"April 11, 2014",3.01
22,23.,"""Girls Like You""[48]",Maroon 5,"May 31, 2018",3.01
23,24.,"""Let Her Go""[49]",Passenger,"July 25, 2012",2.97
24,25.,"""Mi Gente""[50]",J Balvin,"June 29, 2017",2.90
25,26.,"""Wheels on the Bus""[51]",Cocomelon – Nursery Rhymes,"May 24, 2018",2.88
26,27.,"""Hello""[52]",Adele,"October 22, 2015",2.83
27,28.,"""Perfect""[53]",Ed Sheeran,"November 9, 2017",2.82
28,29.,"""Waka Waka (This Time for Africa)""[54]",Shakira,"June 4, 2010",2.80
29,30.,"""Axel F""[55]",Crazy Frog,"June 16, 2009",2.77

## 2. Scrape the details of team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/. You need to find following details: Match Title, Series, Place, Date, Time. Note: - From bcci.tv home page you have to reach to the international fixtures page through code.

In [4]:
# Function Definition
def cricket_fixtures(url):
    driver = webdriver.Chrome("C:\\chromedriver.exe")
    driver.get(url)
    time.sleep(8)
    
    international = driver.find_element_by_xpath("//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover']")
    international.click()
    time.sleep(4)
    fixtures = driver.find_element_by_xpath("//a[@class='navigation__link navigation__link--in-drop-down']")
    fixtures.click()
    delay=10
    WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CLASS_NAME,'js-list')))
    
#     extracting all the cricket matches url
    match_href = []
    for i in driver.find_elements_by_xpath("//div[@class='js-list']/a"):
        match_href.append(i.get_attribute('href'))
    
#     Let's create empty lists to store necessary information
    match_title = []
    series = []
    place=[]
    date = []
    mat_time = []
    
    for url in match_href:
        driver.get(url)
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CLASS_NAME,'mc-header-info__match-description')))
        
#         extracting match_title
        mt = driver.find_element_by_xpath("//p[@class='mc-header-info__match-description']")
        match_title.append(mt.text.replace(' VIEW SERIES',''))
        
#         extracting series
        s = driver.find_element_by_xpath("//h1[@class='mc-header-info__title']/strong")
        series.append(s.text)
        
#         extracting place
        md = [] # Match Details
        for i in driver.find_elements_by_xpath("//div[@class='match-info__details']/ul/li[3]/span[2]"):
            md.append(i)
        place.append(md[1].text)
        
#         extracting date
        d = driver.find_element_by_xpath("//div[@class='mc-header-scorebox__datetime']/strong")
        date.append(d.text)
        
#         extracting match time
        t = driver.find_element_by_xpath("//div[@class='mc-header-scorebox__datetime']/span[1]")
        mat_time.append(t.text)

    df = pd.DataFrame({})
    df['Match_Title']=match_title
    df['Series']=series
    df['Place']=place
    df['Date']=date
    df['Time']=mat_time
    
    driver.close()
    
    return df


# Calling Function
cricket_fixtures('https://www.bcci.tv/')

,Match_Title,Series,Place,Date,Time
0,FINAL - ICC WORLD TEST CHAMPIONSHIP FINAL,India v New Zealand,"The Ageas Bowl, Southampton",Friday 18 June,15:30 IST
1,1ST TEST - ENGLAND V INDIA 2021,England v India,"Trent Bridge, Nottingham",Wednesday 4 August,15:30 IST
2,2ND TEST - ENGLAND V INDIA 2021,England v India,"Lord's, London",Thursday 12 August,15:30 IST
3,3RD TEST - ENGLAND V INDIA 2021,England v India,"Headingley, Leeds",Wednesday 25 August,15:30 IST
4,4TH TEST - ENGLAND V INDIA 2021,England v India,"The Oval, London",Thursday 2 September,15:30 IST
5,5TH TEST - ENGLAND V INDIA 2021,England v India,"Old Trafford, Manchester",Friday 10 September,15:30 IST

## 3. Scrape the details of selenium exception from guru99.com.Url = https://www.guru99.com/. You need to find following details:Name, Description. Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [3]:
# Function Definition
def Selenium_Exception(url):
    driver = webdriver.Chrome("C:\\chromedriver.exe")
    driver.get(url)
    time.sleep(8)
    
#     clicking selenium
    sele = []
    for i in driver.find_elements_by_xpath("//li[@class='fa fa-chevron-circle-right']/a"):
        sele.append(i)   
    for i in sele:
        if i.text == 'Selenium':
            i.click()
            break
    
    delay=10
    WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CLASS_NAME,'table')))
    
#     Clicking Selenium Exception Handling Tutorial
    tutorials = []
    for i in driver.find_elements_by_xpath("//table[@class='table']/tbody/tr/td/a"):
        tutorials.append(i)
    for i in tutorials:
        if i.get_attribute('title')=='Selenium Exception Handling (Common Exceptions List)':
            url = i.get_attribute('href')
            driver.get(url)
            break
    
    delay=10
    WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CLASS_NAME,'page-header')))
    
#     Let's create empty lists to store necessary information
    exception_name = []
    description = []
    
#     extracting exception_name
    for i in driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]"):
        exception_name.append(i.text)
    
#     extracting description
    for i in driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]"):
        description.append(i.text)
    
    df = pd.DataFrame({})
    df['Exception_Name']=exception_name[1:]
    df['Description']=description[1:]
    
    driver.close()
    
    return df


# Calling Function
Selenium_Exception('https://www.guru99.com/')

,Exception_Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

## 4. Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/. You have to find following details: Rank, State, GSDP(19-20), GSDP(18-19), Share, GDP(Billion). Note: - From statisticstimes home page you have to reach to economy page through code.

In [3]:
# Function Definition
def GDP(url):
    driver = webdriver.Chrome("C:\\chromedriver.exe")
    driver.get(url)
    delay=10
    WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CLASS_NAME,'dropbtn')))
    
#     clicking economy
    button = []
    for i in driver.find_elements_by_xpath("//button[@class='dropbtn']"):
        button.append(i)
    for i in button:
        if i.text=='Economy':
            i.click()
            break
    
    delay=10
    WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CLASS_NAME,'dropdown-content')))
    
#     clicking India
    dropdown_content = []
    for i in driver.find_elements_by_xpath("//div[@class='dropdown-content']/a"):
        dropdown_content.append(i)
    for i in dropdown_content:
        if i.text=='India':
            url = i.get_attribute('href')
            driver.get(url)
            break
    
    delay=10
    WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CLASS_NAME,'ec')))
    
#     clicking GDP of Indian states
    content = []
    for i in driver.find_elements_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']/li/a"):
        content.append(i)
    for i in content:
        if i.text=='» GDP of Indian states':
            url = i.get_attribute('href')
            driver.get(url)
            break
    
    delay=10
    WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CLASS_NAME,'fwidth')))
    
#     extracting information
    info=[]
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td"):
        info.append(i.text)
    
    df = pd.DataFrame({})
    df['Rank']=info[0:264:8]
    df['State']=info[1:264:8]
    df['GSDP(19-20)']=info[2:264:8]
    df['GSDP(18-19)']=info[3:264:8]
    df['Share(18-19)']=info[4:264:8]
    df['GDP($ Billion)']=info[5:264:8]
    
    driver.close()
    
    return df


# Calling Function
GDP('http://statisticstimes.com/')

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP($ Billion)
0,1,Maharashtra,-,"2,632,792",13.88%,398.145
1,2,Tamil Nadu,"1,845,853","1,630,208",8.59%,246.529
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.35%,239.656
3,4,Gujarat,-,"1,502,899",7.92%,227.276
4,5,Karnataka,"1,631,977","1,493,127",7.87%,225.798
5,6,West Bengal,"1,253,832","1,089,898",5.75%,164.820
6,7,Rajasthan,"1,020,989","942,586",4.97%,142.543
7,8,Andhra Pradesh,"972,782","862,957",4.55%,130.501
8,9,Telangana,"969,604","861,031",4.54%,130.210
9,10,Madhya Pradesh,"906,672","809,592",4.27%,122.431
10,11,Kerala,-,"781,653",4.12%,118.206
11,12,Delhi,"856,112","774,870",4.08%,117.180
12,13,Haryana,"831,610","734,163",3.87%,111.024
13,14,Bihar,"611,804","530,363",2.80%,80.204
14,15,Punjab,"574,760","526,376",2.77%,79.601
15,16,Odisha,"521,275","487,805",2.57%,73.768
16,17,Assam,-,"315,881",1.67%,47.769
17,18,Chhattisgarh,"329,180","304,063",1.60%,45.982
18,19,Jharkhand,"328,598","297,204",1.57%,44.945
19,20,Uttarakhand,-,"245,895",1.30%,37.186
20,21,Jammu & Kashmir,-,"155,956",0.82%,23.584
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.265
22,23,Goa,"80,449","73,170",0.39%,11.065
23,24,Tripura,"55,984","49,845",0.26%,7.538
24,25,Chandigarh,-,"42,114",0.22%,6.369
25,26,Puducherry,"38,253","34,433",0.18%,5.207
26,27,Meghalaya,"36,572","33,481",0.18%,5.063
27,28,Sikkim,"32,496","28,723",0.15%,4.344
28,29,Manipur,"31,790","27,870",0.15%,4.215
29,30,Nagaland,-,"27,283",0.14%,4.126
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.721
31,32,Mizoram,"26,503","22,287",0.12%,3.370
32,33,Andaman & Nicobar Islands,-,-,-,-

## 5. Scrape the details of trending repositories on Github.com. Url = https://github.com/. You have to find the following details: Repository title, Repository description, Contributors count, Language used. Note: - From the home page you have to click on the trending option from Explore menu through code.

In [4]:
# Function Definition
def github(url):
    driver = webdriver.Chrome("C:\\chromedriver.exe")
    driver.get(url)
    time.sleep(8)
    
#     clicking Explore
    button = []
    for i in driver.find_elements_by_xpath("//summary[@class='HeaderMenu-summary HeaderMenu-link px-0 py-3 border-0 no-wrap d-block d-lg-inline-block']"):
        button.append(i)
    for i in button:
        if i.text=='Explore':
            i.click()
            break
    
#     clicking Trending
    trending=driver.find_element_by_xpath("//a[@class='py-2 lh-condensed-ultra d-block Link--secondary no-underline f5 Bump-link--hover' and @data-ga-click='(Logged out) Header, go to Trending']").get_attribute('href')
    driver.get(trending)
    
    delay=10
    WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH,"//h1[@class='h3 lh-condensed']/a")))
    
#     extracting all repositories url
    repository_url=[]
    for i in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
        repository_url.append(i.get_attribute('href'))
    
#     Let's create empty lists to store necessary information
    repository_title=[]
    repository_description=[]
    contributors_count=[]
    language_used=[]

    for url in repository_url:
        driver.get(url)
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH,"//strong[@class='mr-2 flex-self-stretch']/a")))
        
#         extracting repository_title
        rt=driver.find_element_by_xpath("//strong[@class='mr-2 flex-self-stretch']/a")
        repository_title.append(rt.text)
        
#         extracting repository_description
        try:
            rd=driver.find_element_by_xpath("//p[@class='f4 mt-3']")
            repository_description.append(rd.text)
        except NoSuchElementException:
            repository_description.append('-')
        
#         extracting contributors_count
        count=[]
        for i in driver.find_elements_by_xpath("//h2[@class='h4 mb-3']/a"):
            count.append(i.text)
        c=pd.Series(count)
        contributors_count.append(list(c[c.str.contains('Contributors')]))
        
#         extracting language_used
        language=[]
        for i in driver.find_elements_by_xpath("//span[@class='color-text-primary text-bold mr-1']"):
            language.append(i.text)
        language_used.append(", ".join(language))
    
    
    df=pd.DataFrame({})
    df['Repository_Title']=repository_title
    df['Repository_Description']=repository_description
    df['Contributors_Count']=contributors_count
    df['Language_Used']=language_used
    
    driver.close()
    
    return df


# Calling Function
github('https://github.com/')

,Repository_Title,Repository_Description,Contributors_Count,Language_Used
0,supabase,The open source Firebase alternative. Follow t...,[Contributors 92],"TypeScript, JavaScript, CSS, Other"
1,kmm-production-sample,-,[Contributors 3],"Kotlin, Swift"
2,openpilot,openpilot is an open source driver assistance ...,[Contributors 174],"C++, C, Python, Shell, Perl, Makefile, Other"
3,project-layout,Standard Go Project Layout,[Contributors 34],Makefile
4,raydium-ui,-,[Contributors 3],"TypeScript, Vue, Other"
5,twint,An advanced Twitter scraping & OSINT tool writ...,[Contributors 62],"Python, Dockerfile"
6,jd_docker,仅用查看文档,[Contributors 2],"Shell, JavaScript, Dockerfile, Python"
7,JDDJ,"京东到家果园庄园脚本,电报群:https://t.me/joinchat/wH4Ks3mT6...",[],JavaScript
8,slides,it is a repository to store all slides used by...,[],Go
9,SpringAll,循序渐进，学习Spring Boot、Spring Boot & Shiro、Spring ...,[Contributors 2],"Java, HTML, CSS, Other"
10,cs-video-courses,List of Computer Science courses with video le...,[Contributors 44],
11,android_hid,Use Android as Rubber Ducky against another An...,[],Shell
12,leetcode,😏 LeetCode solutions in any programming langua...,[Contributors 68],"Java, Python, C#, C++, JavaScript, Go, Other"
13,flashlight,A C++ standalone library for machine learning,[Contributors 45],"C++, Jupyter Notebook, CMake, Python, Cuda, C,..."
14,Osintgram,Osintgram is a OSINT tool on Instagram. It off...,[Contributors 12],"Python, Makefile, Dockerfile"
15,binance-trading-bot,Automated Binance trading bot - Buy low/Sell h...,[Contributors 5],"JavaScript, CSS, HTML, Dockerfile"
16,javascript-algorithms,📝 Algorithms and data structures implemented i...,[Contributors 139],JavaScript
17,nx,"Powerful, Extensible Dev Tools",[Contributors 270],"TypeScript, JavaScript, Other"
18,winbox,WinBox is a professional HTML5 window manager ...,[Contributors 2],"JavaScript, Less"
19,wave,"Wave - The Software as a Service Starter Kit, ...",[Contributors 2],"PHP, Blade, Shell"
20,HelloGitHub,分享 GitHub 上有趣、入门级的开源项目,[Contributors 11],Python
21,PaddleDetection,Object detection and instance segmentation too...,[Contributors 55],"Python, Jupyter Notebook, C++, Java, Cuda, CMa..."
22,learning-systems-programming-in-rust,「Rustでもわかるシステムプログラミング」,[Contributors 5],Rust
23,terraform-provider-azurerm,Terraform provider for Azure Resource Manager,[Contributors 857],"Go, Other"
24,CheatSheetSeries,The OWASP Cheat Sheet Series was created to pr...,[Contributors 187],"Python, Shell, HTML, Java"

## 6. Scrape the details of top 100 songs on billiboard.com. Url = https://www.billboard.com/. You have to find the following details: Song name, Artist name, Last week rank, Peak rank, Weeks on board. Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [3]:
# Function Definition
def songs(url):
    driver = webdriver.Chrome("C:\\chromedriver.exe")
    driver.get(url)
    time.sleep(8)
    
#     clicking charts
    charts = []
    for i in driver.find_elements_by_xpath("//a[@class='header__main-link header__main-link--charts']"):
        charts.append(i.get_attribute('href'))
    driver.get(charts[0])
    
    delay=10
    WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CLASS_NAME,'charts-landing__info--view-chart-holder')))
    
#     clicking view_chart
    view_chart=driver.find_element_by_xpath("//div[@class='charts-landing__info--view-chart-holder']/div[1]")
    view_chart.click()
    
    delay=10
    WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.CLASS_NAME,'chart-element__information')))
    
#     Let's create empty lists to store necessary information
    song_artist_name=[]
    last_week_rank=[]
    peak_rank=[]
    weeks_on_board=[]
    
#     extracting song_name and artist_name
    for i in driver.find_elements_by_xpath("//span[@class='chart-element__information']/span"):
        song_artist_name.append(i.text)
    
#     extracting last_week_rank
    for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']"):
        last_week_rank.append(i.text)
    
#     extracting peak_rank
    for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']"):
        peak_rank.append(i.text)
    
#     extracting weeks_on_board
    for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']"):
        weeks_on_board.append(i.text)
    
    df=pd.DataFrame({})
    df['Song_Name']=song_artist_name[::3]
    df['Artist_Name']=song_artist_name[1::3]
    df['Last_Week_Rank']=last_week_rank
    df['Peak_Rank']=peak_rank
    df['Weeks_On_Board']=weeks_on_board
    
    driver.close()
    
    return df


# Calling Function
songs('https://www.billboard.com/')

,Song_Name,Artist_Name,Last_Week_Rank,Peak_Rank,Weeks_On_Board
0,Rapstar,Polo G,1,1,2
1,Leave The Door Open,Silk Sonic (Bruno Mars & Anderson .Paak),3,1,7
2,Peaches,Justin Bieber Featuring Daniel Caesar & Giveon,4,1,5
3,Montero (Call Me By Your Name),Lil Nas X,2,1,4
4,Levitating,Dua Lipa Featuring DaBaby,6,5,29
...,...,...,...,...,...
95,Go!,Moneybagg Yo Featuring BIG30,-,96,1
96,Drankin N Smokin,Future & Lil Uzi Vert,-,31,12
97,Monsters,All Time Low Featuring Demi Lovato & blackbear,95,55,17
98,Slatty,Young Thug & Gunna Featuring Yak Gotti & Lil Duke,-,99,1
99,4 Da Gang,42 Dugg & Roddy Ricch,84,67,3

## 7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/. You have to find the following details:Name, Designation, Company, Skills they hire for, Location. Note: - From naukri.com homepage click on the recruiters option and the on the search panel type Data science and click on search. All this should be done through code.

In [3]:
# Function Definition
def jobs(url):
    driver = webdriver.Chrome("C:\\chromedriver.exe")
    driver.get(url)
    time.sleep(8)
    
#     clicking recruiters
    recruiters=driver.find_element_by_xpath("//a[@title='Search Recruiters']").get_attribute('href')
    driver.get(recruiters)
    time.sleep(6)
    
#     searching Data Science
    search_bar=driver.find_element_by_xpath("//div[@id='skill']/div/div[2]/input")
    search_bar.send_keys('Data Science')
    search_butn=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
    search_butn.click()
    time.sleep(6)
    
#     extracting all jobs url
    href=[]
    for i in driver.find_elements_by_xpath("//a[@class='ellipsis' and @target='_blank']"):
        href.append(i.get_attribute('href'))
    
#     Let's create empty lists to store necessary information
    name=[]
    designation=[]
    company_location=[]
    skills_required=[]

    for url in href:
        driver.get(url)
        delay=10
        WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH,"//h1[@class='fl ellipsis wLimit hd']")))
        
#         extracting name
        try:
            n=driver.find_element_by_xpath("//h1[@class='fl ellipsis wLimit hd']")
            name.append(n.text)
        except NoSuchElementException:
            name.append("-")
        
#         extracting designation
        try:
            d=driver.find_element_by_xpath("//div[@class='ellipsis']")
            designation.append(d.text)
        except NoSuchElementException:
            designation.append("-")
        
#         extracting company and location
        try:
            for i in driver.find_elements_by_xpath("//div[@class='oh']/a"):
                company_location.append(i.text)
        except NoSuchElementException:
            company_location.append("-")

#         extracting skills_required
        try:
            s=driver.find_element_by_xpath("//div[@class='fl lPortn']/p[1]")
            skills_required.append(s.text)
        except NoSuchElementException:
            skills_required.append("-")
        
        df=pd.DataFrame({})
    df['Name']=name
    df['Designation']=designation
    df['Company']=company_location[::2]
    df['Skills_Required']=skills_required
    df['Location']=company_location[1::2]
    
    driver.close()
    
    return df


# Calling Function
jobs('https://www.naukri.com/')

,Name,Designation,Company,Skills_Required,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer , Internet Marketing Pro...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net , Java , Data Science , Linux Administrat...",Hyderabad / Secunderabad
2,Talent Acquisition Executive,Recruitment Professional,XenonStack,"Web Designing , html5 , Angular.js , seo , had...",Chandigarh
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,", Mean Stack , javascript , angularjs , mongod...",Ahmedabad
4,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Mid Level, Junior Level",Pune
5,subhas patel,Founder & CEO,LibraryXProject,"Hadoop , Spark , Digital Strategy , Data Archi...",UK - (london)
6,Abhishek - Only Analytics Hiring - India and APAC,Recruitment - Lead Consultant,Apidel Technologies Division of Transpower,"Analytics , Business Intelligence , Business A...",Vadodara / Baroda
7,Institute for Financial Management and Research,Programme Manager,IFMR,Analytics & Business Intelligence,Chennai
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning , algorithms , Go Getter , Co...",Trivandrum
9,Asif Lucknowi,Director,Weupskill- Live Wire India,-,Indore
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Junior Level, Mid Level",Bengaluru / Bangalore
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa , Ui , ux , Java Developer , Java Architect...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,-,Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,-,Mumbai
14,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,IT Skills,Nagpur
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Junior Level, Mid Level",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data , Hadoop , Data Analytics , Data Science",Bhopal
17,Priya Khare,Senior Manager,Independent Consultant,-,Bengaluru / Bangalore
18,Manisha Yadav,HR Executive,Easi Tax,Mid Level,Navi Mumbai
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,IT-Software/Software Services,Cochin
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE LIMITED,"Mid Level, Top Mangement Level",Delhi
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics , Data Science , Machine Learni...",Hyderabad / Secunderabad
22,Rithika dadwal,HR Recruiter,Affine Analytics,"Junior Level, Mid Level",Pune
23,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Mid Level, High Level",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"High Level, Mid Level",Pune
25,Shaun Rao,Manager - Human Resources,Exela Technologies,"Java , Net , Angularjs , Hr , Infrastructure ,...",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private Limited,"High Level, Top Mangement Level",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science , Hadoop , Rpas , Devops , Python...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing , Machine Learning , Neural ...",Others
29,Rajat Kumar,Founder & CEO,R.S Consultancy & Services,"Web Technologies , Project Management , Softwa...",Delhi
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"S. Finance Manager , Freshers , Experience , S...",Bengaluru / Bangalore
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics , Managed Services , Team Leading",Mysoru / Mysore
32,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,-,Hyderabad / Secunderabad
33,Prateek Kumar,Head,Trisect,Junior Level,Noida
34,Amit Sharma,Consultant,ASCO consulting,-,New Delhi
35,Kanan,senior technology instructor,NY INST,"Mid Level, Junior Level",Chennai
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research & Consulting Co. India,-,Aligarh
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Junior Level, High Level",Salt Lake City
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Python , Php , Qa Automation , Ui , Wordpre",Pune
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,-,Bengaluru / Bangalore
40,Ankit Sinha,Head-Analytics,Suntech Global,-,Mumbai
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Top Mangement Level, Junior Level",Indore
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science , Node.js , Angularjs",Bengaluru / Bangalore
43,Ashwini,"Director, Global Delivery",MRP Advisers,-,MYSORE
44,Balaji Kolli,Co-Founder,Saras Solutions India Pvt Ltd,-,Hyderabad / Secunderabad
45,Rajani Nagaraj,HR Manager,WildJasmine,"java , hadoop , r , Machine Learning , spark ,...",Bengaluru / Bangalore
46,ROHIT Kumar,Architect,LNT Private Limited,"Mid Level, High Level",Mumbai
47,Amir Chowdhury,Managing Partner,Granular.ai,-,
48,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,-,Noida
49,Sunny Sharma,Managing Director - HR,Western Service Providers,"Software Professionals , Engineering , Technic...",Mumbai

## 8. Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/. You have to find the following details:Book name, Author name, Volumes sold, Publisher, Genre.

In [4]:
# Function Definition
def books(url):
    driver = webdriver.Chrome("C:\\chromedriver.exe")
    driver.get(url)
    time.sleep(8)
    
#     extracting all the information 
    info = []
    for i in driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td"):
        info.append(i.text)
    
    df=pd.DataFrame({})
    df['Book name']=info[1::6]
    df['Author name']=info[2::6]
    df['Volumes sold']=info[3::6]
    df['Publisher']=info[4::6]
    df['Genre']=info[5::6]
    
    driver.close()
    
    return df


# Calling Function
books('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/')

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

## 9. Scrape the details of most watched tv series of all time from imdb.com.Url = https://www.imdb.com/list/ls095964455/. You have to find the following details:Name, Year span, Genre, Run time, Ratings, Votes.

In [5]:
def tv_series(url):
    driver = webdriver.Chrome("C:\\chromedriver.exe")
    driver.get(url)
    time.sleep(8)
    
#     Let's create empty lists to store necessary information
    name =[]
    year_span =[]
    genre=[]
    run_time=[]
    ratings=[]
    votes=[]
    
#     extracting name
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
        name.append(i.text)
    
#     extracting year_span
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]"):
        year_span.append(i.text)
    
#     extracting genre
    for i in driver.find_elements_by_xpath("//span[@class='genre']"):
        genre.append(i.text)
    
#     extracting run_time
    for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
        run_time.append(i.text)
    
#     extracting ratings
    for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]"):
        ratings.append(i.text)
    
#     extracting votes
    for i in driver.find_elements_by_xpath("//span[@name='nv']"):
        votes.append(i.text)
    
    df=pd.DataFrame({})
    df['Name']=name
    df['Year_Span']=year_span
    df['Genre']=genre
    df['Run_Time']=run_time
    df['Ratings']=ratings
    df['Votes']=votes
    
    driver.close()
    
    return df


# Calling Function
tv_series('https://www.imdb.com/list/ls095964455/')

,Name,Year_Span,Genre,Run_Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.3,"1,802,840"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"847,917"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"867,968"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"260,276"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"221,258"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,220"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"54,682"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"165,514"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.2,"34,589"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"188,226"

## 10. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/. You have to find the following details: Dataset name, Data type, Task, Attribute type, No of instances,  No of attributes, Year. Note: - from the home page you have to go to the Show All Dataset page through code.

In [7]:
# Function Definition
def uci_repositories(url):
    driver = webdriver.Chrome("C:\\chromedriver.exe")
    driver.get(url)
    time.sleep(8)
    
#     clicking View_ALL_Data_Sets
    View_ALL_Data_Sets=driver.find_element_by_xpath("//span[@class='whitetext']/a/font")
    View_ALL_Data_Sets.click()
    time.sleep(8)
    
#     Let's create empty lists to store necessary information
    name=[]
    data_type=[]
    task=[]
    attribute_type=[]
    no_of_instances=[]
    no_of_attributes=[]
    year=[]
    
#     extracting all Data_Sets url
    href=[]
    for i in driver.find_elements_by_xpath("//b/a"):
        href.append(i.get_attribute('href'))
    
    for url in href:
        driver.get(url)
        try:
            delay=10
            WebDriverWait(driver, delay).until(EC.presence_of_element_located((By.XPATH,"//span[@class='heading']/b")))
        except TimeoutException:
            continue
        
#         extracting name
        try:
            for i in driver.find_elements_by_xpath("//span[@class='heading']/b"):
                name.append(i.text)
        except NoSuchElementException:
            name.append('-')
        
#         extracting data_type
        try:
            content=[]
            for i in driver.find_elements_by_xpath("//tr/td[2]/p"):
                content.append(i.text)
            data_type.append(content[0])
        except NoSuchElementException:
            data_type.append('-')
        
#         extracting task
        try:
            content=[]
            for i in driver.find_elements_by_xpath("//tr/td[2]/p"):
                content.append(i.text)
            task.append(content[2])
        except NoSuchElementException:
            task.append('-')
        
#         extracting attribute_type
        try:
            content=[]
            for i in driver.find_elements_by_xpath("//tr/td[2]/p"):
                content.append(i.text)
            attribute_type.append(content[1])
        except NoSuchElementException:
            attribute_type.append('-')

#         extracting no_of_instances
        try:
            content=[]
            for i in driver.find_elements_by_xpath("//tr/td[4]/p"):
                content.append(i.text)
            no_of_instances.append(content[0])
        except NoSuchElementException:
            no_of_instances.append('-')
        
#         extracting no_of_attributes
        try:
            content=[]
            for i in driver.find_elements_by_xpath("//tr/td[4]/p"):
                content.append(i.text)
            no_of_attributes.append(content[1])
        except NoSuchElementException:
            no_of_attributes.append('-')
        
#         extracting year
        try:
            content=[]
            for i in driver.find_elements_by_xpath("//tr/td[6]/p"):
                content.append(i.text)
            year.append(content[1])
        except NoSuchElementException:
            year.append('-')
    
    df=pd.DataFrame({})
    df['Name']=name
    df['Data_Type']=data_type
    df['Task']=task
    df['Attribute_Type']=attribute_type
    df['No_of_Instances']=no_of_instances
    df['No_of_Attributes']=no_of_attributes
    df['Year']=year
    
    driver.close()
    
    return df


# Calling Function
uci_repositories('https://archive.ics.uci.edu/')

,Name,Data_Type,Task,Attribute_Type,No_of_Instances,No_of_Attributes,Year
0,Abalone Data Set,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995-12-01
1,Adult Data Set,Multivariate,Classification,"Categorical, Integer",48842,14,1996-05-01
2,Annealing Data Set,Multivariate,Classification,"Categorical, Integer, Real",798,38,N/A
3,Anonymous Microsoft Web Data Data Set,N/A,Recommender-Systems,Categorical,37711,294,1998-11-01
4,Arrhythmia Data Set,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998-01-01
...,...,...,...,...,...,...,...
578,in-vehicle coupon recommendation Data Set,Multivariate,Classification,N/A,12684,23,2020-09-15
579,Gait Classification Data Set,Multivariate,Classification,Real,48,321,2020-10-14
580,Wikipedia Math Essentials Data Set,Time-Series,Regression,Real,731,1068,2021-04-20
581,Wikipedia Math Essentials Data Set,Time-Series,Regression,Real,731,1068,2021-04-20
582,Synchronous Machine Data Set Data Set,Multivariate,Regression,Real,557,5,2021-04-21